### ISSUE TITLE
Rollup failed to resolve import

### ISSUE THREAD

**Issue by zAlweNy26** [matthewp/astro-fastify#10]
Hi, I'm trying to build for production, but I get this error when I do `astro check && tsc --noEmit && astro build`:

```
[vite]: Rollup failed to resolve import "C:UsersdanynDocumentsGitHubexplorershandbook
ode_modules@matthewpastro-fastifylibserver.js" from "@astrojs-ssr-virtual-entry".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

 I did what he said:

```js
vite: {
  build: {
    rollupOptions: {
      external: fileURLToPath(new URL('node_modules/@matthewp/astro-fastify/lib/server.js', import.meta.url))
    }
  }
}
```

But I still get the error.

**Comment by zAlweNy26** [comment]
Sì sto utilizzando Windows 11, niente a che fare con `astro check`, solo un problema di `astro build`.

**Comment by espimarisa** [comment]
Hey @matthewp, I can confirm that this is still an issue today - on Windows 10 22H2, pnpm 8.0.0, and Node v20. Running v2.1.5 of the package.

Does not happen with astro check, only happens with astro build. I get the same exact type of error, and adding the path to external does nothing to fix the issue.

Definitely worth looking into, seems like a pretty big roadblock currently.

**Comment by matthewp** [comment]
Would love a PR if anyone has time to look at this  themselves.

**Comment by solelychloe** [comment]
@matthewp I figured out why this is happening. I fixed this by appending double forward slashes to the path.
