### ISSUE TITLE
Content-Encoding: none

### ISSUE THREAD

**Issue by smnbbrv** [matthewp/astro-fastify#24]
hi @matthew2 , just found out in the SSR adapter for fastify the following lines:

https://github.com/matthewp/astro-fastify/blob/6b5ef371c0a57ee3e80eae60f643e0b2192a143a/lib/server.js#L58C1-L60C8

Why would we do that? Is there a reason behind? I'm compressing the data on a reverse proxy and because of this header it simply does not compress anything.

It also seems like an obsolete action, this header is not anyhow required AFAIK

Do I miss something? 

Thanks a lot! 

**Possible workaround:**

Currently I reset the content-type header to actually bypass this condition

```js
Astro.response.headers.set('Content-Type', 'text/html; charset=utf-8');
```

**Comment by matthewp** [comment]
Hm, looking at the blame isn't very helpful here. I can't recall why I did this. Probably because whatever project I was working on at the time needed it. But I think I agree with you that we shouldn't be doing it. So would be happy to accept a PR to change it. Thanks!
