### ISSUE TITLE
[Question] - Astro in Exsiting Fastify Server

### ISSUE THREAD

**Issue by rmcarias** [matthewp/astro-fastify#28]
Hey @matthewp, I saw your youtube a while ago with Matt Collina in where you were adding Astro to an existing Fastify server. Is that something this can be used for? I want to use Astro as my templating system and Fastify as the routing system. Any guidance is appreciated. Thanks

**Comment by matthewp** [comment]
No, this is the opposite of that. You probably want to look at https://github.com/mcollina/fastify-astro/issues/1 (still in design phase).
