### ISSUE TITLE
Not working with Astro 4.0

### ISSUE THREAD

**Issue by Gradlon** [matthewp/astro-fastify#29]
The Module is not working with Astro 4.0.
Astro throws this error.

The adapter @matthewp/astro-fastify:adapter doesn't provide a feature map. It is required in Astro 4.0.

**Comment by matthewp** [comment]
Thanks, please submit a PR if you'd like to see Astro 4 support.

**Comment by matthewp** [comment]
Ah yes, I'll do that now.

**Comment by matthewp** [comment]
3.1.0 is out.

**Comment by smnbbrv** [comment]
Thanks! :)
