### ISSUE TITLE
Inject variables from fastify middleware?

### ISSUE THREAD

**Issue by coryvirok** [matthewp/astro-fastify#8]
Hello and thanks for this adapter! 

I'd like to be able to add Middleware to my astro endpoints. Eg. I'd like to add something like `request.user` to the request that my astro endpoint processes.

I was excited by this adapter because it works in dev mode however I don't see a way to inject variables from a fastify middleware/or hook, (eg onRequest) so that it is available to my astro endpoints.

Is this possible?

Thanks

**Comment by matthewp** [comment]
No, not at this time. Astro doesn't have a middleware concept that adapters can participate in.

**Comment by coryvirok** [comment]
kk, thanks
